Skripchenkoveta hometask 4
iTechArt-RubyLab/Ruby-Lab pull request #101
Opened 2021-11-18 08:46 UTC by skripchenkoVeta

2021-11-22 19:28 UTC, jtethras requested changes
Both Array extensions and custom Hash are not implemented correctly. Let's get back to this task once you're ready!

2021-11-22 19:32 UTC, skripchenkoVeta commented
okay, thanks

2021-11-25 23:30 UTC, jtethras commented on skripchenkoveta/hometask-4/my_hash.rb
> +  def get(index, key)
🥇

2021-11-29 11:29 UTC, jtethras approved these changes
Great work! Love the new benchmarks and updates on the array extensions!

2021-11-29 11:37 UTC, merged