Slavahaim/hometask 4
iTechArt-RubyLab/Ruby-Lab pull request #107
Opened 2021-11-18 14:08 UTC by Slavahaim

Add hometask 4.1

2021-11-18 15:46 UTC, PFDeve commented on Slavahaim/hometask-4/my_array_rotate.rb
> +  def lab_rotate(slip = 1)
Looks like we can rename `slip` like `offset`

2021-11-18 15:46 UTC, PFDeve commented on Slavahaim/hometask-4/my_array_rotate.rb
> +    if slip.zero? || (slip == length)
It's cool that you consider all conditions but `(slip == length)`is redundant because further in the code, your algorithm solves this problem without this condition.

2021-11-18 15:46 UTC, PFDeve commented on Slavahaim/hometask-4/my_array_rotate.rb
> +  def lab_rotate!(slip = 1)
offset

2021-11-18 15:46 UTC, PFDeve commented on Slavahaim/hometask-4/my_array_rotate_benchmark.rb
> +  x.report('native') { (1..1000).to_a.rotate!(232) }
Could you add for `100_000` & `1_000_000`

2021-11-19 11:58 UTC, Slavahaim commented
benchmark  Array rotate:
       user     system      total        real
100_000..1_000_000
custom  0.049541   0.009530   0.059071 (  0.059069)
native    0.027369   0.000000   0.027369 (  0.027374)
custom  0.017195   0.008492   0.025687 (  0.025692)
native    0.014724   0.012004   0.026728 (  0.026734)
custom  0.026867   0.000000   0.026867 (  0.026876)
native    0.032728   0.000000   0.032728 (  0.032753)
100_000..1_000_000
custom  0.027080   0.000000   0.027080 (  0.027084)
native    0.025328   0.008912   0.034240 (  0.034248)
custom  0.021470   0.000000   0.021470 (  0.021476)
native    0.021807   0.000000   0.021807 (  0.021832)
custom  0.032390   0.000000   0.032390 (  0.032395)
native    0.021624   0.000000   0.021624 (  0.021634)

2021-11-19 11:59 UTC, Slavahaim commented
benchmark my_hash vs Hash
       user     system      total        real
write Hash
   0.000038   0.000006   0.000044 (  0.000038)
   0.000194   0.000031   0.000225 (  0.000223)
   0.001824   0.000300   0.002124 (  0.002124)
write MyHash
   0.000704   0.000115   0.000819 (  0.000820)
   0.047869   0.000000   0.047869 (  0.047871)
   2.555300   0.000000   2.555300 (  2.558093)
read Hash
   0.000000   0.000004   0.000004 (  0.000002)
   0.000000   0.000002   0.000002 (  0.000001)
   0.000000   0.000002   0.000002 (  0.000002)
read MyHash
   0.000000   0.000026   0.000026 (  0.000027)
   0.000000   0.000093   0.000093 (  0.000093)
   0.000000   0.000762   0.000762 (  0.000764)

2021-11-19 12:14 UTC, PFDeve requested changes
Lets do it hash via hash table and keep in mind hash collision

https://ru.wikipedia.org/wiki/%D0%A5%D0%B5%D1%88-%D1%82%D0%B0%D0%B1%D0%BB%D0%B8%D1%86%D0%B0

2021-11-19 12:14 UTC, PFDeve commented on Slavahaim/hometask-4/my_hash.rb
> +    @my_hash = []
We have `attr_reader, attr_writer & attr_accessor` in ruby. In your case we should use `attr_reader` accessor. Lets correct it

2021-11-19 12:14 UTC, PFDeve commented on Slavahaim/hometask-4/my_hash.rb
> +    pair(input_key)[1]
1 is a magic number. Lets extract into constant

2021-11-19 12:14 UTC, PFDeve commented on Slavahaim/hometask-4/my_hash.rb
> +      @my_hash.find { |key, _value| key == input_key }[1] = input_value
the same magic number

2021-11-19 12:14 UTC, PFDeve commented on Slavahaim/hometask-4/my_hash.rb
> +  include Enumerable
Lets add new line between 6 & 7 lines

2021-11-23 15:34 UTC, PFDeve approved these changes

2021-11-23 15:37 UTC, merged