Sillitski/hometask_4
iTechArt-RubyLab/Ruby-Lab pull request #111
Opened 2021-11-18 15:26 UTC by qqqwww123cdv

2021-11-18 15:46 UTC, jekapulpit requested changes

2021-11-18 15:46 UTC, jekapulpit commented on qqqwww123cdv/hometask-4/my-array-rotate/my_array_rotate_benchmark.rb
> +  x.report { (1..100).to_a.lab_rotate(10) }
let's use array size increasingly (e.g. from 10 to 10000) to have more decent statistics

2021-11-18 15:46 UTC, jekapulpit commented on qqqwww123cdv/hometask-4/my-hash/my_hash.rb
> +    @hash = reject { |value| value.include? key }
`Hash#delete` returns deleted value

2021-11-18 15:46 UTC, jekapulpit commented on qqqwww123cdv/hometask-4/my-hash/my_hash.rb
> +    @hash = reject { |value| value }
we need just to pass a truthy value in `reject`, so using the argument is redundant here

2021-11-18 15:46 UTC, jekapulpit commented on qqqwww123cdv/hometask-4/my-hash/my_hash_benchmark.rb
> +  x.report { 100.times { |value| my_hash[value] = value } }
also here, let's use values increasingly

2021-11-21 12:49 UTC, qqqwww123cdv commented
![image](https://user-images.githubusercontent.com/56838340/142762479-38f8e56e-6066-4db6-8d26-a637aa9edcef.png)

2021-11-21 22:08 UTC, jekapulpit approved these changes

2021-11-22 04:34 UTC, merged