hometask-5
iTechArt-RubyLab/Ruby-Lab pull request #116
Opened 2021-11-21 12:51 UTC by AndrewTehan

[hometask-5](https://docs.google.com/document/d/1DyuPaRI2wiw-bCOg3Ht0XbQsLr_PZnIR2vIr0O8nfNU/edit)

2021-11-21 12:55 UTC, AndrewTehan commented
Codecademy SQL course is completed
![image](https://user-images.githubusercontent.com/70772646/142762635-1ed064d5-2d56-4c45-841a-c4f219413f81.png)

2021-11-21 17:43 UTC, hannazspot requested changes

2021-11-21 17:43 UTC, hannazspot commented on AndrewTehan/hometask-5/4_2.sql
> +select * from film
films and languages are connected with 1-1 relationship, so `AND` doesn't suit there

2021-11-21 17:43 UTC, hannazspot commented on AndrewTehan/hometask-5/4_3.sql
> +select concat(first_name, '-', last_name) as fullname from actor
<img width="559" alt="Screen Shot 2021-11-21 at 8 28 42 PM" src="https://user-images.githubusercontent.com/31599278/142772629-9b475556-dcdd-4f51-b039-2b75a8a7fb66.png">

2021-11-21 17:43 UTC, hannazspot commented on AndrewTehan/hometask-5/4_7.sql
> +  set description = 'Dune tells the story of Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, who must travel to the most dangerous
<img width="596" alt="Screen Shot 2021-11-21 at 8 33 19 PM" src="https://user-images.githubusercontent.com/31599278/142772785-680e424a-e9c7-4dd4-808e-725450490e03.png">

2021-11-22 13:36 UTC, hannazspot commented on AndrewTehan/hometask-5/4_2.sql
> +  or l.name = 'Italian';
instead of such amount of `OR` operators, you may use `IN`

2021-11-22 13:53 UTC, hannazspot approved these changes

2021-11-22 13:56 UTC, merged