silitski_hometask/5
iTechArt-RubyLab/Ruby-Lab pull request #137
Opened 2021-11-22 17:40 UTC by qqqwww123cdv

Finished 5 homework.

2021-11-23 11:04 UTC, jekapulpit requested changes

2021-11-23 11:04 UTC, jekapulpit commented on qqqwww123cdv/hometask-5/3.sql
> +WHERE first_name LIKE 'W%' OR last_name LIKE '%H';
I don't think that the anyone's last name ends on `H`, it's `h` probably 😄

2021-11-23 11:04 UTC, jekapulpit commented on qqqwww123cdv/hometask-5/4.sql
> +GROUP BY 1;
let's be more clear in the grouping section here, just a number brings some confusion

2021-11-23 11:04 UTC, jekapulpit commented on qqqwww123cdv/hometask-5/4.sql
> +SELECT DISTINCT rental_duration, COUNT(title) AS in_each_group
why do we need `DISTINCT` here?

2021-11-23 11:04 UTC, jekapulpit commented on qqqwww123cdv/hometask-5/5.sql
> +SELECT name, COUNT(film_id) AS number_of_films
let's specify column names in front of fields if we have more than one table in our selection

2021-11-24 09:41 UTC, jekapulpit approved these changes, later dismissed

2021-11-24 13:29 UTC, jekapulpit approved these changes

2021-11-24 13:32 UTC, qqqwww123cdv commented
silitski_hometask/5

2021-11-24 13:32 UTC, merged