Silitski/hometask2
iTechArt-RubyLab/Ruby-Lab pull request #37
Opened 2021-11-07 15:39 UTC by qqqwww123cdv

Сompleted second homework.

2021-11-07 16:55 UTC, jekapulpit requested changes

2021-11-07 16:55 UTC, jekapulpit commented on hometask-2/get_middle_charachter.rb
> +  hf = str.length / 2
let's try to name this variable more accurately? `hf` gives not many information 😄

2021-11-07 16:55 UTC, jekapulpit commented on hometask-2/get_middle_charachter.rb
> +  if str.length.even?
we can use ternary operator there and your 5 lines will become 1

2021-11-07 16:55 UTC, jekapulpit commented on hometask-2/get_middle_charachter.rb
> +    str[hf - 1] + str[hf]
and if you'll choose the ternary operator, the range looks better here `str[(hf - 1)..hf]`

2021-11-08 09:18 UTC, ramantechart requested changes
https://github.com/iTechArt-RubyLab/Ruby-Lab#%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-2

2021-11-08 16:31 UTC, closed without merging