Skripchenkoveta hometask 2
iTechArt-RubyLab/Ruby-Lab pull request #42
Opened 2021-11-07 21:27 UTC by skripchenkoVeta

add run cli project

2021-11-08 16:37 UTC, jtethras requested changes
Overall looks good! But there is a potential for improvements. Please study following articles, improve whatever you find appropriate, and comment what you think :)

https://www.rubyguides.com/2018/10/puts-vs-print/
https://github.com/rubocop/ruby-style-guide#accessormutator-method-names (I know it's not a class here, but anyway I suggest to think on alternative naming)

Also, when you write your commit message, try to answer a question "What are these changes for?" and use present tense to answer the question. How would your rename your previous commit?

2021-11-08 16:37 UTC, jtethras commented on skripchenkoveta/hometask-2/get_middle_charachter.rb
> +    break if str == 'exit!'
When you directly compare something to a _particular_ value, it's better to store this value somewhere in a const and compare with a const. This way, when you use this value multiple times in a project and at some point need to update this value, you won't have to search through your code and update it everywhere, but only update the const value.

2021-11-08 18:30 UTC, skripchenkoVeta commented
> Overall looks good! But there is a potential for improvements. Please study following articles, improve whatever you find appropriate, and comment what you think :)
> 
> https://www.rubyguides.com/2018/10/puts-vs-print/ https://github.com/rubocop/ruby-style-guide#accessormutator-method-names (I know it's not a class here, but anyway I suggest to think on alternative naming)

The name of the method is not quite correct. It would be more correct to write 'midString' or 'middleString', right? Or just without 'get' , but then 'middle' name does not say what this method is about.

Also using 'p' instead of 'puts' (or 'print'), but it would be more correct to use 'puts' here. My code is already finished 'not debugging'

2021-11-08 18:40 UTC, skripchenkoVeta commented
> Also, when you write your commit message, try to answer a question "What are these changes for?" and use present tense to answer the question. How would your rename your previous commit?

Okay:)
I get it and will fix it

2021-11-10 20:04 UTC, jtethras approved these changes
🥇

2021-11-10 20:55 UTC, merged