create hello_world.rb
iTechArt-RubyLab/Ruby-Lab pull request #5
Opened 2021-11-03 20:15 UTC by PandaGrom

2021-11-03 21:16 UTC, ramantechart requested changes
Этот файл не является исполняемым.
Переименуй PR в PandaGrom hometask 1.

2021-11-04 13:43 UTC, ramanspaceos approved these changes

2021-11-04 13:46 UTC, ramantechart approved these changes

2021-11-04 14:16 UTC, nieisnuje approved these changes

2021-11-08 09:18 UTC, merged