Mlshvch hometask 2
iTechArt-RubyLab/Ruby-Lab pull request #56
Opened 2021-11-09 13:28 UTC by mlshvch

I've completed Ruby-Lab hometask-2 with described requirements.

2021-11-09 23:07 UTC, StalemateInc requested changes
Why does your PR contains both the first and the second home tasks? Please synchronize your fork and update the branch to have only the second one.

2021-11-09 23:07 UTC, StalemateInc commented on mlshvch/hometask-2/get_middle_character.rb
> +  len = string.length
`len` is not the best variable name. Letters are free those days, so you might as well call it `length` or anything more descriptive than `len`.

2021-11-09 23:07 UTC, StalemateInc commented on mlshvch/hometask-2/get_middle_character.rb
> +  mid = len / 2
Same applies for `mid` and other obscure variable names.

2021-11-09 23:07 UTC, StalemateInc commented on mlshvch/hometask-2/get_middle_character.rb
> +  len = string.length
Also, useless variable assignment, this could easily be a part of the line below. You don't use the result of `len` in the scope of this method anywhere else.

2021-11-09 23:07 UTC, StalemateInc commented on mlshvch/hometask-2/get_middle_character.rb
> +  len.even? == true ? string[mid - 1, mid] : string[mid]
`if` conditions, in both full and ternary forms, by nature check if their body is equal to `true` or `false` to determine a code path. You don't have to write `... == true` manually, `if`/`unless` conditions will do it for you.

Please revise the following:
* how conditional statements work in Ruby (you can find the info in lecture materials)
* what types are treated as `true` and `false` in conditional statements (same as above, find in lectures).
* what return type is expected from method calls ending with a questionmark (spoiler alert - it's _usually_ true or false)

...and change the code accordingly.

2021-11-09 23:07 UTC, StalemateInc commented on mlshvch/hometask-2/get_middle_character.rb
> +    puts 'Enter string: '
Since you are using `puts` and read input starting from the next line, the extra space in the end of your string is useless.

2021-11-09 23:07 UTC, StalemateInc commented on mlshvch/hometask-2/get_middle_character.rb
> +  mid = len / 2
Also try to avoid magic numbers in future. Any numeric literal without an explicit purpose introduces confusion in future, so it's usually better to move them into constants or, for simple cases like this one, indicate the purpose with the variable name. Something like:
```ruby
middle_string_position = string.length / 2 # now it's more obvious why we are dividing by 2, we are looking for a middle!
```

2021-11-09 23:07 UTC, StalemateInc commented on mlshvch/hometask-2/get_middle_character.rb
> +    if input.empty? == true
The same comment about conditional statements also applies here.

2021-11-09 23:07 UTC, StalemateInc commented on mlshvch/hometask-2/get_middle_character.rb
> +    break if input == 'exit!'
It's usually a good practice to move non-interpolated strings (e.g. plain messages or some important strings like `exit!`) to constants to avoid reinstantiation and emphasize their importance. This way it's also much easier to find and change such strings later :)

2021-11-09 23:07 UTC, StalemateInc commented on mlshvch/hometask-2/get_middle_character.rb
> +    end
Can probably be shortened to a ternary operation.

2021-11-09 23:07 UTC, StalemateInc commented on mlshvch/hometask-2/get_middle_character.rb
> +  len.even? == true ? string[mid - 1, mid] : string[mid]
Also, in idiomatic Ruby the usage of ranges is welcome when it comes to defining intervals, so getting a substring could be also written as:
```ruby
string[(mid-1)..mid]
```

2021-11-10 11:22 UTC, mlshvch commented on mlshvch/hometask-2/get_middle_character.rb
> +    break if input == 'exit!'
What practice is the best: to make only the first letter capital, or the whole constant?

2021-11-10 11:24 UTC, mlshvch commented
Will be better to  push changes as a new commit or refactor previous commits?

2021-11-10 11:28 UTC, mlshvch commented on mlshvch/hometask-2/get_middle_character.rb
> +    end
In case of ternary operation, length of line will be 104 characters, that is bigger than 80

2021-11-10 14:44 UTC, StalemateInc commented on mlshvch/hometask-2/get_middle_character.rb
> +    break if input == 'exit!'
It depends on a context. Usually constants are named in all caps, names in camel case are reserved for classes and modules. Here is [a small excerpt from the book](excerpt) which describes such conventions.

2021-11-10 14:44 UTC, StalemateInc commented on mlshvch/hometask-2/get_middle_character.rb
> +    end
All right, let's leave it as is not to violate the code style.

2021-11-10 14:45 UTC, StalemateInc commented
> Will be better to push changes as a new commit or refactor previous commits?

Another commit with addressing the changes will be enough.

2021-11-13 16:20 UTC, closed without merging