hometask 2
iTechArt-RubyLab/Ruby-Lab pull request #91
Opened 2021-11-16 10:04 UTC by AlexeyShparun

upload hometask 2

2021-11-16 10:07 UTC, ramantechart requested changes
This PR contains commits from hometask-1

2021-11-16 17:06 UTC, fayriss commented on AlexeyShparun/hometask-2/get_middle_charachter.rb
> +    str[str.length / 2 - 1] + str[str.length / 2]
`str.length / 2` is repeated 3 times

Consider making a variable for this value

2021-11-16 17:09 UTC, fayriss commented on AlexeyShparun/hometask-2/get_middle_charachter.rb
> +    str[str.length / 2]
You can make this code cleaner by using Ranges
Example:
```ruby
str = "012"
str[1..1] #=> "1"

str = "0123"
str[1..2] #=> "12"
```

2021-11-17 12:47 UTC, fayriss approved these changes

2021-11-17 13:09 UTC, ramantechart approved these changes

2021-11-17 13:21 UTC, merged